// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PS.Template.AccessData;

namespace PS.Template.AccessData.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20211204015128_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PS.Template.Domain.Entities.Tipo", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TipoId");

                    b.ToTable("Tipos");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Descripcion = "Administrador"
                        },
                        new
                        {
                            TipoId = 2,
                            Descripcion = "Medico"
                        },
                        new
                        {
                            TipoId = 3,
                            Descripcion = "Cliente"
                        });
                });

            modelBuilder.Entity("PS.Template.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Dni")
                        .HasMaxLength(8)
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.HasIndex("TipoId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Apellido = "Corrales",
                            Contraseña = "1234",
                            Correo = "manuelcorrales@gmail.com",
                            Direccion = "Calle manuel 123",
                            Dni = 12345678,
                            Nombre = "Manuel",
                            NombreUsuario = "manuel123",
                            Telefono = 42202223,
                            TipoId = 3
                        },
                        new
                        {
                            UsuarioId = 5,
                            Apellido = "Rensi",
                            Contraseña = "1234",
                            Correo = "camilorensi@gmail.com",
                            Direccion = "Calle camilo 123",
                            Dni = 123456700,
                            Nombre = "Camilo",
                            NombreUsuario = "camilo123",
                            Telefono = 42202000,
                            TipoId = 3
                        },
                        new
                        {
                            UsuarioId = 10,
                            Apellido = "Perez",
                            Contraseña = "1234",
                            Correo = "juanperez@gmail.com",
                            Direccion = "Calle juan 123",
                            Dni = 12340000,
                            Nombre = "Juan",
                            NombreUsuario = "juan123",
                            Telefono = 42005555,
                            TipoId = 2
                        });
                });

            modelBuilder.Entity("PS.Template.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("PS.Template.Domain.Entities.Tipo", "Tipos")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipos");
                });

            modelBuilder.Entity("PS.Template.Domain.Entities.Tipo", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
